export const mockBroker = {
  id: '1',
  name: 'Alexandra Voss',
  title: 'Luxury Real Estate Advisor',
  tagline: 'An uncompromising standard of real estate excellence.',
  bio: 'Alexandra Voss brings over two decades of unparalleled expertise to the Los Angeles luxury real estate market.\n\nHer nuanced understanding of the discrete needs of ultra-high-net-worth individuals makes her the premier choice for buying and selling trophy estates in Beverly Hills, Bel-Air, and Malibu.\n\nWith a client roster including industry leaders, celebrities, and international investors, Alexandra\'s reputation is built on absolute discretion, strategic marketing, and record-breaking results.',
  shortBio: 'Alexandra Voss is a premier luxury real estate advisor specializing in exclusive properties across Beverly Hills, Bel-Air, and Malibu. With over $2.4B in career sales, she delivers unparalleled discretion, market insight, and results for the world\'s most discerning clientele.',
  phone: '(310) 555-0142',
  email: 'alexandra@alexandravoss.com',
  photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80',
  serviceAreas: ['Beverly Hills', 'Bel-Air', 'Malibu'],
  licenseNumber: 'DRE #01928374',
} as any

export const mockProperties = [
  {
    id: 'p1',
    title: 'Modern Masterpiece in Bel-Air',
    slug: 'modern-masterpiece-bel-air',
    description: 'A stunning architectural triumph featuring sweeping city-to-ocean views, zero-edge pool, and bespoke finishes throughout.',
    price: 24500000,
    status: 'FOR_SALE',
    address: '1042 Bel Air Road',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90077',
    bedrooms: 6,
    bathrooms: 8,
    squareFeet: 12500,
    lotSize: 1.5,
    yearBuilt: 2023,
    propertyType: 'SINGLE_FAMILY',
    amenities: ['Zero-edge pool', 'Home theater', 'Wine cellar', 'Smart home automation'],
    images: [{ url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=90', alt: 'Exterior' }],
    neighborhood: { name: 'Bel-Air', slug: 'bel-air', description: 'An exclusive, ultra-private enclave nestled in the foothills of the Santa Monica Mountains, known for its sprawling properties and hidden mansions.' },
  },
  {
    id: 'p2',
    title: 'Beverly Hills Estate',
    slug: 'beverly-hills-estate',
    description: 'Classic elegance meets modern luxury in this meticulously restored 1920s Spanish Colonial Revival.',
    price: 18900000,
    status: 'JUST_LISTED',
    address: '901 N Alpine Dr',
    city: 'Beverly Hills',
    state: 'CA',
    zip: '90210',
    bedrooms: 7,
    bathrooms: 9,
    squareFeet: 10200,
    lotSize: 0.8,
    yearBuilt: 1928,
    propertyType: 'LUXURY_ESTATE',
    amenities: ['Tennis court', 'Guest house', 'Library', 'Formal dining'],
    images: [{ url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=90', alt: 'Pool area' }],
    neighborhood: { name: 'Beverly Hills', slug: 'beverly-hills', description: 'The epitome of luxury living, featuring palm-lined streets, world-class shopping on Rodeo Drive, and some of the most prestigious estates in the world.' },
  },
  {
    id: 'p3',
    title: 'Malibu Oceanfront Retreat',
    slug: 'malibu-oceanfront-retreat',
    description: 'Private beachfront sanctuary on prestigious Carbon Beach with expansive decks and seamless indoor-outdoor living.',
    price: 32000000,
    status: 'FOR_SALE',
    address: '22400 Pacific Coast Hwy',
    city: 'Malibu',
    state: 'CA',
    zip: '90265',
    bedrooms: 5,
    bathrooms: 6,
    squareFeet: 6800,
    lotSize: 0.3,
    yearBuilt: 2015,
    propertyType: 'SINGLE_FAMILY',
    amenities: ['Private beach access', 'Oceanfront deck', 'Spa', 'Chef\'s kitchen'],
    images: [{ url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=90', alt: 'Ocean view' }],
    neighborhood: { name: 'Malibu', slug: 'malibu', description: '21 miles of scenic coastline offering a relaxed, affluent lifestyle with pristine beaches and breathtaking oceanfront architecture.' },
  }
] as any[]

export const mockSoldProperties = [
  {
    id: 's1',
    title: 'Trousdale Estates Contemporary',
    slug: 'trousdale-estates',
    status: 'SOLD',
    price: 15000000,
    soldPrice: 15500000,
    soldDate: new Date('2023-10-15'),
    city: 'Beverly Hills',
    state: 'CA',
    bedrooms: 4,
    bathrooms: 5,
    squareFeet: 7200,
    images: [{ url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=90', alt: 'Exterior' }],
  },
  {
    id: 's2',
    title: 'Brentwood Park Traditional',
    slug: 'brentwood-park',
    status: 'SOLD',
    price: 12500000,
    soldPrice: 12250000,
    soldDate: new Date('2023-08-22'),
    city: 'Los Angeles',
    state: 'CA',
    bedrooms: 6,
    bathrooms: 7,
    squareFeet: 8500,
    images: [{ url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=90', alt: 'Front yard' }],
  }
] as any[]

export const mockNeighborhoods = [
  {
    id: 'n1',
    name: 'Beverly Hills',
    slug: 'beverly-hills',
    tagline: 'The pinnacle of prestige living',
    heroImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
    description: 'The epitome of luxury living, featuring palm-lined streets, world-class shopping on Rodeo Drive, and some of the most prestigious estates in the world.',
    lifestyle: 'Iconic, manicured, and exceptionally glamorous. Residents enjoy immediate access to Michelin-starred dining, exclusive boutiques, and pristine parks.',
    marketOverview: 'Beverly Hills remains a cornerstone of global luxury real estate. The market is characterized by steady appreciation and high demand for turnkey estates north of Sunset Boulevard.',
    highlights: ['Rodeo Drive Shopping', 'Beverly Hills Hotel', 'Top-tier public schools', 'Unparalleled security'],
    featured: true,
    properties: [],
    _count: { properties: 12 },
  },
  {
    id: 'n2',
    name: 'Bel-Air',
    slug: 'bel-air',
    tagline: 'Ultra-private enclave in the hills',
    heroImage: 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&q=80',
    description: 'An exclusive, ultra-private enclave nestled in the foothills of the Santa Monica Mountains, known for its sprawling properties and hidden mansions.',
    lifestyle: 'Discrete and tranquil. A haven for those seeking ultimate privacy away from the city\'s hustle, while still being minutes away from Westwood and Beverly Hills.',
    marketOverview: 'Bel-Air commands some of the highest price per square foot in the nation. The market consists largely of large acreage estates and significant architectural properties.',
    highlights: ['Bel-Air Country Club', 'Hotel Bel-Air', 'Utmost privacy', 'Spectacular views'],
    featured: true,
    properties: [],
    _count: { properties: 8 },
  },
  {
    id: 'n3',
    name: 'Malibu',
    slug: 'malibu',
    tagline: '21 miles of scenic coastline',
    heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    description: '21 miles of scenic coastline offering a relaxed, affluent lifestyle with pristine beaches and breathtaking oceanfront architecture.',
    lifestyle: 'Laid-back coastal luxury. Residents embrace an active outdoor lifestyle centered around the ocean, surfing, and the Santa Monica Mountains.',
    marketOverview: 'Malibu real estate is highly diverse, ranging from exclusive beachfront enclaves like Carbon Beach to sprawling equestrian estates in the canyons.',
    highlights: ['Nobu Malibu', 'Surfrider Beach', 'Equestrian trails', 'Oceanfront dining'],
    featured: true,
    properties: [],
    _count: { properties: 5 },
  }
] as any[]

export const mockTestimonials = [
  {
    id: 't1',
    clientName: 'Sarah & Michael T.',
    review: 'Alexandra\'s knowledge of the Beverly Hills market is truly unmatched. She found us an off-market property that perfectly matched our rigorous criteria and handled the negotiation with absolute precision and grace. A true professional.',
    transactionType: 'Buyer',
    createdAt: new Date('2023-11-10'),
    rating: 5,
  },
  {
    id: 't2',
    clientName: 'David L.',
    review: 'Selling a luxury estate requires a nuanced approach. Alexandra\'s marketing strategy was brilliant, securing international exposure and ultimately a record-breaking price for our neighborhood in Bel-Air.',
    transactionType: 'Seller',
    createdAt: new Date('2023-09-05'),
    rating: 5,
  }
] as any[]

export const mockInsights = [
  {
    id: 'i1',
    title: 'The Rise of Off-Market Luxury Transactions',
    slug: 'off-market-luxury',
    excerpt: 'Why ultra-high-net-worth individuals are increasingly turning to private, whisper listings to buy and sell trophy properties.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    coverImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
    publishedAt: new Date(),
    readTime: 5,
    author: 'Alexandra Voss',
    tags: ['Market Trends', 'Luxury'],
  }
] as any[]

export const mockMedia = [
  {
    id: 'm1',
    publication: 'Wall Street Journal',
    title: 'Top 100 Real Estate Agents in America',
    url: '#',
    date: new Date('2023-12-01'),
  },
  {
    id: 'm2',
    publication: 'Architectural Digest',
    title: 'Inside a $32M Malibu Masterpiece',
    url: '#',
    date: new Date('2023-10-15'),
  },
  {
    id: 'm3',
    publication: 'Los Angeles Times',
    title: 'Record Breaking Sale in Bel-Air',
    url: '#',
    date: new Date('2023-08-20'),
  }
] as any[]
